server:
  port: 8000

spring:
  cloud:
    nacos:
      discovery:
        server-addr=: 127.0.0.1:8848 # nacos注册中心地址
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.0.105:3306/mall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: mall-menber  # 注册中心服务名称
mybatis-plus:
  # classpath加个* : 其他引入的类路径也扫描
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 主键自增

