server:
  port: 10000

spring:
  cloud:
    nacos:
      discovery:
        server-addr=: 127.0.0.1:8848 # nacos注册中心地址
    alicloud:
      access-key: LTAI4G5WZfgz5UT6b4o6f7FL
      secret-key: L78uXRhwrqoT3qQ9QQGxzsiKeCsrDX
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.0.106:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: mall-product  # 注册中心服务名称
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  # 时间格式返回设置

mybatis-plus:
  # classpath加个* : 其他引入的类路径也扫描
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 主键自增
      # 逻辑删除配置
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
logging:
  level:
    # 显示sql语句
    com.sour.mall.product: debug
